---
apiVersion: v1
kind: Namespace
metadata:
  name: cdro
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "sc-cdro" 
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  provisioningMode: efs-ap
  fileSystemId: "fs-08ab0c2ca203b8fa1"
  directoryPerms: "777"
  gid: "0"
  uid: "0"
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "cdro-server-pvc"
  namespace: "cdro"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "sc-cdro"
  resources:
    requests:
      storage: "20Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "cdro-repo-pvc"
  namespace: "cdro"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "sc-cdro"
  resources:
    requests:
      storage: "20Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "cdro-agent-pvc"
  namespace: "cdro"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "sc-cdro"
  resources:
    requests:
      storage: "5Gi"
---
apiVersion: v1
kind: Secret
metadata:
  name: "cdro-cred"
  namespace: "cdro"
type: Opaque
data:
  CBF_SERVER_USER: YWRtaW4=        # Base64-encoded "admin"
  CBF_SERVER_PASSWORD: Y2hhbmdlbWU=  # Base64-encoded "changeme"
  CBF_SERVER_ADMIN_PASSWORD: Y2hhbmdlbWU=  # Base64-encoded "changeme"
