apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: cdro
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: 'https://github.com/daeung0921/kust-cdro-install.git'
    path: .
    targetRevision: v6.0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cdro
  ignoreDifferences:
  - group: "apps"
    kind: "Deployment"
    name: "flow-server"
    jsonPointers:
    - /spec/replicas     
  syncPolicy:
    #automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
