namespace: cdro

resources:
- additional_resources.yaml

helmCharts:
- name: postgresql
  namespace: cdro
  valuesFile : ./postgre-values.yaml
  repo: https://charts.bitnami.com/bitnami
  version: 13.2.24
  releaseName: postgre 
  IncludeCRDs: true
- name: cloudbees-flow
  namespace: cdro
  valuesFile : ./cdro-values.yaml
  repo: https://public-charts.artifacts.cloudbees.com/repository/public
  version: 2.27.0
  releaseName: cdro 
  IncludeCRDs: true

patches:
  - target:
      kind: Ingress
      name: flow-ingress
    patch: |
      - op: replace
        path: /apiVersion
        value: networking.k8s.io/v1
      - op: add
        path: /spec/rules/0/http/paths/0/pathType
        value: ImplementationSpecific
      - op: add
        path: /spec/rules/0/http/paths/1/pathType
        value: ImplementationSpecific
      - op: replace
        path: /spec/rules/0/http/paths/0/backend
        value:
          service:
            name: flow-web
            port: 
              number: 80 
      - op: replace
        path: /spec/rules/0/http/paths/1/backend
        value:
          service:
            name: flow-web
            port: 
              number: 80 
      - op: add
        path: /spec/ingressClassName
        value: alb
      - op: replace
        path: /metadata/annotations
        value:
          alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:960249453675:certificate/5ef7ac4b-8549-480b-ac9b-6efae081ecbf"
          alb.ingress.kubernetes.io/group.name: "cdro-cloudbees-flow"
          alb.ingress.kubernetes.io/healthcheck-path: "/auth/"
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
          alb.ingress.kubernetes.io/scheme: "internet-facing"
          alb.ingress.kubernetes.io/ssl-redirect: "443"
          alb.ingress.kubernetes.io/target-type: "ip"
          external-dns.alpha.kubernetes.io/hostname: "cdro.idtplateer.com"
#  - target:
#      kind: Deployment
#      name: flow-web
#    patch: |
#      - op: add
#        path: /spec/template/spec/volumes
#        value:
#          configMap:
#            defaultMode: 420
#            name: php-ini-config
#      - op: add
#        path: /spec/template/spec/containers/0/volumeMounts
#        value:
#          mountPath: /custom-config/apache/php.ini
#          name: php-ini-config
#          subPath: php-ini-config