namespace: cdro

resources:
- additional_resources.yaml

helmCharts:
- name: postgresql
  namespace: cdro
  valuesFile : ./postgre-values.yaml
  repo: https://charts.bitnami.com/bitnami
  version: 13.2.24
  releaseName: postgre 
  IncludeCRDs: true
- name: cloudbees-flow
  namespace: cdro
  valuesFile : ./cdro-values.yaml
  repo: https://public-charts.artifacts.cloudbees.com/repository/public
  version: 2.27.0
  releaseName: cdro 
  IncludeCRDs: true

#patches:
#  - target:
#      kind: Ingress
#      name: flow-ingress
#    patch: |
#      - op: replace
#        path: /apiVersion
#        value: networking.k8s.io/v1

patchesStrategicMerge:
  - |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: flow-ingress
      namespace: cdro
    spec:
      rules:
      - http:
          paths:
          - pathType: ImplementationSpecific
          - pathType: ImplementationSpecific