---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cdro-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cdro-ca-cert
spec:
  commonName: datahub
  isCA: true
  issuerRef:
    kind: Issuer
    name: cdro-issuer
  secretName: cdro-ca-cert
  subject:
    organizations:
      - Qwant
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme: 
    email: daeung@plateer.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef: 
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx